version: 2
jobs:
  build:
    branches:
      only:
        - dev
    working_directory: ~/DemoWebSource
    docker:
      - image: circleci/node:10-browsers
    steps:
      - add_ssh_keys:
          fingerprints:
            - "fe:d9:a3:c9:e7:b4:16:f2:19:ad:0f:b8:3c:b4:6f:ec"
      - checkout
      - restore_cache:
          key: DemoWebSource-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run: npm install
      - save_cache:
          key: DemoWebSource-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - "node_modules"
      - run: npm run test -- --no-watch --no-progress --code-coverage
      - store_artifacts:
          path: coverage
          destination: coverage
      # - run: npm run build -- --prod
      - run: git config --global user.email "jef15938@gmail.com"
      - run: git config --global user.name "jef15938"
      - run: npx ng deploy --no-silent
      # - run:
      #     name: Creating Dummy Artifacts
      #       command: |
      #         echo "my artifact file" > /dist;
      #         mkdir /dist;
      #         # echo "my artifact files in a dir" > /tmp/artifacts/artifact-2;
      # - store_artifacts:
      #   path: /DemoWebSource/dist
      #   destination: /dist