jobs:
  test:
    working_directory: ~/DemoWebSource
    docker:
      - image: circleci/node:10-browsers
    steps:
      - checkout
      - restore_cache:
          key: DemoWebSource-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run: npm install
      - save_cache:
          key: DemoWebSource-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - "node_modules"
      - run: npm run test -- --no-watch --no-progress --code-coverage
      - store_artifacts:
          path: coverage
          destination: coverage

  merge-to-master:
    working_directory: ~/DemoWebSource
    docker:
      - image: circleci/node:10-browsers
    steps:
      - checkout
      - run: git config --global user.email "jef15938@gmail.com"
      - run: git config --global user.name "jef15938"
      - run: npx ng deploy --no-silent --base-href=/DemoWebSource/
      - run: git checkout master
      - run: git merge dev && git push origin/master
  
  deploy:
    working_directory: ~/DemoWebSource
    docker:
      - image: circleci/node:10-browsers
    steps:
      - add_ssh_keys:
          fingerprints:
            - "98:4d:55:4f:82:0b:84:c3:86:ac:8b:bd:2f:3b:f8:c9"
      - checkout
      - restore_cache:
          key: DemoWebSource-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run: npm install
      - save_cache:
          key: DemoWebSource-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - "node_modules"
      - run: git config --global user.email "jef15938@gmail.com"
      - run: git config --global user.name "jef15938"
      - run: npx ng deploy --no-silent --base-href=/DemoWebSource/

workflows:
  version: 2
  test-and-deploy:
    jobs: 
      - test:
          filters:
            branches:
              only:
                - dev
      - merge-to-master:
          filters:
            branches:
              only:
                - dev
          requires:
            - test
      - deploy:
          filters:
            branches:
              only:
                - master