version: 2
jobs:
  build:
    branches:
      only:
        - dev
    working_directory: ~/DemoWebSource
    docker:
      - image: circleci/node:10-browsers
    steps:
      - checkout
      - restore_cache:
          key: DemoWebSource-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run: npm install
      - save_cache:
          key: DemoWebSource-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - "node_modules"
      - run: npm run test -- --no-watch --no-progress
      - run: ng build --prod
      - run:
          name: Creating Dummy Artifacts
            command: |
              echo "my artifact file" > /dist;
              mkdir /dist;
              # echo "my artifact files in a dir" > /tmp/artifacts/artifact-2;
      - store_artifacts:
        path: /DemoWebSource/dist
        destination: /dist