# This is a basic workflow to help you get started with Actions

name: UpdateReadMe & Push to master

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  updateReadme_MergeToMaster:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          ref: 'dev'
      # Runs a single command using the runners shell
      - name: npm install
        run: npm install
      
      - name: updateReadme
        run: npm run updateReadme

      # Runs a set of commands using the runners shell
      - name: push to dev
        run: |
          git config --global user.email "jef15938@gmail.com"
          git config --global user.name "jef15938"
          git add .
          git commit -m "update README" || true
          git push
          git log -1
          
      - uses: actions/checkout@v2
        with:
          ref: 'master'
      - name: merge to master
        run: |
          git config --global user.email "jef15938@gmail.com"
          git config --global user.name "jef15938"
          git pull origin master --allow-unrelated-histories
          git log -1
          git log origin/dev -1
          git merge origin/dev && git push
